# mappings.py

TICKER_MAPPINGS = {
    "Apple Inc. (AAPL)": "AAPL",
    "Microsoft Corporation (MSFT)": "MSFT",
    "NVIDIA Corporation (NVDA)": "NVDA",
    "Amazon.com Inc. (AMZN)": "AMZN",
    "Meta Platforms Inc. (META)": "META",
    "Alphabet Inc. Class A (GOOGL)": "GOOGL",
    "Alphabet Inc. Class C (GOOG)": "GOOG",
    "Berkshire Hathaway Inc. (BRK-B)": "BRK-B",
    "Tesla Inc. (TSLA)": "TSLA",
    "Broadcom Inc. (AVGO)": "AVGO",
    "Eli Lilly and Company (LLY)": "LLY",
    "JPMorgan Chase & Co. (JPM)": "JPM",
    "UnitedHealth Group Inc. (UNH)": "UNH",
    "Visa Inc. (V)": "V",
    "Exxon Mobil Corporation (XOM)": "XOM",
    "Mastercard Inc. (MA)": "MA",
    "Johnson & Johnson (JNJ)": "JNJ",
    "Procter & Gamble Co. (PG)": "PG",
    "The Home Depot Inc. (HD)": "HD",
    "Costco Wholesale Corporation (COST)": "COST",
    "Merck & Co. Inc. (MRK)": "MRK",
    "AbbVie Inc. (ABBV)": "ABBV",
    "Chevron Corporation (CVX)": "CVX",
    "Salesforce Inc. (CRM)": "CRM",
    "Advanced Micro Devices Inc. (AMD)": "AMD",
    "PepsiCo Inc. (PEP)": "PEP",
    "Netflix Inc. (NFLX)": "NFLX",
    "Bank of America Corp (BAC)": "BAC",
    "Coca-Cola Company (KO)": "KO",
    "Thermo Fisher Scientific Inc. (TMO)": "TMO",
    "Adobe Inc. (ADBE)": "ADBE",
    "Walmart Inc. (WMT)": "WMT",
    "McDonald's Corporation (MCD)": "MCD",
    "Walt Disney Co (DIS)": "DIS",
    "Cisco Systems Inc. (CSCO)": "CSCO",
    "Abbott Laboratories (ABT)": "ABT",
    "Intuit Inc. (INTU)": "INTU",
    "Qualcomm Inc. (QCOM)": "QCOM",
    "Intel Corporation (INTC)": "INTC",
    "Verizon Communications Inc. (VZ)": "VZ",
    "Comcast Corporation (CMCSA)": "CMCSA",
    "Danaher Corporation (DHR)": "DHR",
    "Pfizer Inc. (PFE)": "PFE",
    "ServiceNow Inc. (NOW)": "NOW",
    "Amgen Inc. (AMGN)": "AMGN",
    "International Business Machines (IBM)": "IBM",
    "Texas Instruments Inc. (TXN)": "TXN",
    "Boeing Company (BA)": "BA",
    "S&P Global Inc. (SPGI)": "SPGI",
    "General Electric Company (GE)": "GE",
    "Philip Morris International (PM)": "PM",
    "Honeywell International Inc. (HON)": "HON",
    "ConocoPhillips (COP)": "COP",
    "Intuitive Surgical Inc. (ISRG)": "ISRG",
    "Union Pacific Corporation (UNP)": "UNP",
    "Caterpillar Inc. (CAT)": "CAT",
    "Nike Inc. (NKE)": "NKE",
    "RTX Corporation (RTX)": "RTX",
    "Goldman Sachs Group Inc. (GS)": "GS",
    "Stryker Corporation (SYK)": "SYK",
    "Lowe's Companies Inc. (LOW)": "LOW",
    "BlackRock Inc. (BLK)": "BLK",
    "Progressive Corporation (PGR)": "PGR",
    "TJX Companies Inc. (TJX)": "TJX",
    "Medtronic PLC (MDT)": "MDT",
    "Citigroup Inc. (C)": "C",
    "American Express Company (AXP)": "AXP",
    "Boston Scientific Corporation (BSX)": "BSX",
    "Vertex Pharmaceuticals (VRTX)": "VRTX",
    "Charter Communications Inc. (CHTR)": "CHTR",
    "Lockheed Martin Corporation (LMT)": "LMT",
    "Chubb Limited (CB)": "CB",
    "Marsh & McLennan Companies (MMC)": "MMC",
    "Gilead Sciences Inc. (GILD)": "GILD",
    "Deere & Company (DE)": "DE",
    "Bristol-Myers Squibb Company (BMY)": "BMY",
    "Automatic Data Processing (ADP)": "ADP",
    "Analog Devices Inc. (ADI)": "ADI",
    "Starbucks Corporation (SBUX)": "SBUX",
    "Mondelez International Inc. (MDLZ)": "MDLZ",
    "CVS Health Corporation (CVS)": "CVS",
    "Prologis Inc. (PLD)": "PLD",
    "Lam Research Corporation (LRCX)": "LRCX",
    "Global Payments Inc. (GPN)": "GPN",
    "Cigna Group (CI)": "CI",
    "Zoetis Inc. (ZTS)": "ZTS",
    "Altria Group Inc. (MO)": "MO",
    "AT&T Inc. (T)": "T",
    "Fiserv Inc. (FI)": "FI",
    "CME Group Inc. (CME)": "CME",
    "Becton Dickinson and Co (BDX)": "BDX",
    "Duke Energy Corporation (DUK)": "DUK",
    "Southern Company (SO)": "SO",
    "Schlumberger N.V. (SLB)": "SLB",
    "EOG Resources Inc. (EOG)": "EOG",
    "Aon plc (AON)": "AON",
    "Regeneron Pharmaceuticals (REGN)": "REGN",
    "Colgate-Palmolive Company (CL)": "CL",
    "Illinois Tool Works Inc. (ITW)": "ITW",
    "Sherwin-Williams Company (SHW)": "SHW",

    # Crypto Mappings
    "Bitcoin (BTC-USD)": "BTC-USD",
    "Ethereum (ETH-USD)": "ETH-USD",
    "Binance Coin (BNB-USD)": "BNB-USD",
    "Solana (SOL-USD)": "SOL-USD",
    "Ripple (XRP-USD)": "XRP-USD",
    "Dogecoin (DOGE-USD)": "DOGE-USD",
    "Cardano (ADA-USD)": "ADA-USD",
    "Tron (TRX-USD)": "TRX-USD",
    "Avalanche (AVAX-USD)": "AVAX-USD",
    "Shiba Inu (SHIB-USD)": "SHIB-USD",
    "Polkadot (DOT-USD)": "DOT-USD",
    "Chainlink (LINK-USD)": "LINK-USD",
    "Bitcoin Cash (BCH-USD)": "BCH-USD",
    "NEAR Protocol (NEAR-USD)": "NEAR-USD",
    "Litecoin (LTC-USD)": "LTC-USD",
    "Uniswap (UNI-USD)": "UNI-USD",
    "Stellar (XLM-USD)": "XLM-USD",
    "Ethereum Classic (ETC-USD)": "ETC-USD",
    "Cosmos (ATOM-USD)": "ATOM-USD",
    "Monero (XMR-USD)": "XMR-USD",
    "Hedera (HBAR-USD)": "HBAR-USD",
    "VeChain (VET-USD)": "VET-USD",
    "Maker (MKR-USD)": "MKR-USD",
    "Aave (AAVE-USD)": "AAVE-USD",
    "Algorand (ALGO-USD)": "ALGO-USD"
}
